### ISSUE TITLE
Xaero's map chest tracker crashed 

### ISSUE THREAD

**Issue by ghost** [fewwan/xaeros-map-chest-tracker-integration#8] opened 2024-06-23 02:29 UTC
### Bug description

When I want to play MineCraft,I saw the mod NEC's screen,it told me to send a report
I don't know what happened

### Steps to reproduce

Launch Minecraft

### Relevant logs

[crash-2024-06-23_10.09.39-client.txt](https://github.com/user-attachments/files/15942332/crash-2024-06-23_10.09.39-client.txt)

### Minecraft version

1.20.4

### Xaero's Map Chest Tracker Integration version

2.0.1

### Chest Tracker version (optional)

2.4.3

### Xaero's Map version (optional)

24.2.0

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by ghost** [comment] 2024-06-23 02:43
more information:
![image](https://github.com/fewwan/xaeros-map-chest-tracker-integration/assets/80134280/74e79e49-a685-4ab4-b804-445101e0579b)

**Comment by fewwan** [comment] 2024-08-16 13:15
Duplicate of #7

**Closed as completed** 2024-08-25 12:52 UTC
Labels: bug
